excluded:
- Pods
disabled_rules:
- trailing_whitespace
- line_length
- identifier_name
- large_tuple
- function_body_length
- type_name
- unused_closure_parameter
opt_in_rules:
- operator_usage_whitespace

force_try:
  severity: warning

force_cast:
  severity: warning

type_body_length:
  - 300
  - 600

file_length:
  - 1000
  - 1500

cyclomatic_complexity:
  - 20
  - 25

custom_rules:
  no_print:
      included: ".*.swift"
      regex: '((\n|\t| |\r|^)print\()'
      name: "No print"
      message: "Use logger.debug (info|verbose) instead"
